os: windows
language: python
python:
  - "3.8"

install:
  - pip install --upgrade pip
  - pip install pyinstaller
  - pip install PyQt5 Pillow keyboard

script:
  - pyinstaller --onefile --noconsole Project0.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist\Project0.exe
  skip_cleanup: true
  on:
    tags: true
