os: windows
language: shell

before_install:
  - choco upgrade chocolatey
  - choco install python --version=3.8 -y

install:
  # Manually update the PATH
  - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
  # Verify Python installation
  - python --version
  # Upgrade pip
  - python -m pip install --upgrade pip
  # Install dependencies
  - pip install pyinstaller
  - pip install PyQt5 Pillow keyboard

script:
  # Build the executable
  - pyinstaller --onefile --noconsole Project0.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist\Project0.exe
  skip_cleanup: true
  on:
    tags: true
